locations = ['Dubai', 'Los Angeles', 'Florida', 'London', 'New York']
print(locations)
locations.sort()
print(locations)
locations.sort(reverse=True)
print(locations)
locations.reverse()
print(locations)
locations.reverse()
print(locations)
locations.sort()
print(locations)
print(locations)
locations.sort(reverse=True)
